version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: senha1p
    volumes:
      - postgresdocker:/var/lib/postgres
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
volumes:
  postgresdocker:
